/*
 * Conduit - a project highlighting CLAP-first development
 *           and exercising the surge synth team libraries.
 *
 * Copyright 2023 Paul Walker and authors in github
 *
 * This file you are viewing now is released under the
 * MIT license as described in LICENSE.md
 *
 * The assembled program which results from compiling this
 * project has GPL3 dependencies, so if you distribute
 * a binary, the combined work would be a GPL3 product.
 *
 * Roughly, that means you are welcome to copy the code and
 * ideas in the src/ directory, but perhaps not code from elsewhere
 * if you are closed source or non-GPL3. And if you do copy this code
 * you will need to replace some of the dependencies. Please see
 * the discussion in README.md for further information on what this may
 * mean for you.
 */

#ifndef CONDUIT_SRC_CHORD_MEMORY_CHORD_MEMORY_H
#define CONDUIT_SRC_CHORD_MEMORY_CHORD_MEMORY_H

#include <clap/helpers/plugin.hh>
#include <atomic>
#include <array>
#include <bitset>
#include <unordered_map>
#include <memory>

#include <memory>
#include "sst/basic-blocks/params/ParamMetadata.h"
#include "conduit-shared/clap-base-class.h"

namespace sst::conduit::chord_memory
{

extern clap_plugin_descriptor desc;
static constexpr int nParams = 1;

struct ConduitChordMemoryConfig
{
    static constexpr int nParams{sst::conduit::chord_memory::nParams};
    static constexpr bool baseClassProvidesMonoModSupport{true};
    static constexpr bool usesSpecializedMessages{false};
    struct PatchExtension
    {
        static constexpr bool hasExtension{true};

        std::array<std::bitset<49>, 128> companionNotes; // the +24 and -24 notes generated by a key

        bool toXml(TiXmlElement &);
        bool fromXml(TiXmlElement *);
    };

    struct DataCopyForUI
    {
        std::atomic<uint32_t> updateCount{0};
        std::atomic<bool> isProcessing{false};
    };

    static clap_plugin_descriptor *getDescription() { return &desc; }
};

struct ConduitChordMemory
    : sst::conduit::shared::ClapBaseClass<ConduitChordMemory, ConduitChordMemoryConfig>
{
    ConduitChordMemory(const clap_host *host);
    ~ConduitChordMemory();

    bool activate(double sampleRate, uint32_t minFrameCount,
                  uint32_t maxFrameCount) noexcept override
    {
        setSampleRate(sampleRate);
        return true;
    }

    enum paramIds : uint32_t
    {
        pmKeyShift = 7241
    };

    bool implementsNotePorts() const noexcept override { return true; }
    uint32_t notePortsCount(bool isInput) const noexcept override { return 1; }
    bool notePortsInfo(uint32_t index, bool isInput,
                       clap_note_port_info *info) const noexcept override;

    clap_process_status process(const clap_process *process) noexcept override;

    bool startProcessing() noexcept override
    {
        uiComms.dataCopyForUI.isProcessing = true;
        uiComms.dataCopyForUI.updateCount++;
        return true;
    }
    void stopProcessing() noexcept override
    {
        uiComms.dataCopyForUI.isProcessing = false;
        uiComms.dataCopyForUI.updateCount++;
    }

  protected:
    std::unique_ptr<juce::Component> createEditor() override;
    std::atomic<bool> refreshUIValues{false};

    std::array<std::array<float, 128>, 16> activeNotes{};
    std::array<std::array<std::bitset<128>, 128>, 16> notesStartedFromParent{};

    // Generate 0 or more output note events from a single input note event
    void handleMIDI1NoteChange(const clap_output_events *ov, const clap_event_midi *under,
                               int16_t channel, int16_t key, double vel, bool on);
    void handleClapNoteChange(const clap_output_events *ov, const clap_event_note *under,
                              int16_t channel, int16_t key, double vel, bool on);

    // If these return TRUE then you need to send a note on or off out.
    bool updateNoteOnOffData(int16_t channel, int16_t key, bool isOn);

  public:
    float *keyShift;
};
} // namespace sst::conduit::chord_memory

#endif // CONDUIT_POLYMETRIC_DELAY_H
